[package]
name = "cargo-playground"
version = "0.1.0"
authors = ["Jonas Finnemann Jensen <jonasfj@google.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "^0.3.7"
